const $=s=>document.querySelector(s), chats=[], history=$('#historyList');
const replies=["Конечно! Я помогу с этим. Вот хороший старт: определите главную цель, выделите самое важное и сделайте первый маленький шаг уже сегодня.","Интересная идея. Я бы посмотрела на неё с трёх сторон: для кого это нужно, какую проблему решает и что сделает опыт по-настоящему запоминающимся.","Готово. Могу также превратить это в подробный план, список задач или более выразительный текст — просто уточните, какой формат вам нужен."];
function addHistory(title){const id=Date.now();chats.unshift({id,title});renderHistory();}
function renderHistory(){history.innerHTML='';chats.forEach(c=>{const n=$('#chatItem').content.cloneNode(true), b=n.querySelector('button');n.querySelector('.history-title').textContent=c.title;b.onclick=e=>{if(e.target.classList.contains('delete-chat')){chats.splice(chats.indexOf(c),1);renderHistory();return}newConversation(false)};history.append(n)})}
function newConversation(add=true){$('#messages').innerHTML='';$('#welcome').style.display='block';if(add) addHistory('Новый разговор');$('#messageInput').focus();closeMenu()}
function message(text,kind){const m=document.createElement('article');m.className='message '+kind;m.innerHTML=`<div class="message-avatar">${kind==='bot'?'✦':'Н'}</div><div class="bubble"></div>`;m.querySelector('.bubble').textContent=text;$('#messages').append(m);$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight;return m}
function send(text){text=text.trim();if(!text)return;$('#welcome').style.display='none';message(text,'user');if(!chats.length)addHistory(text.slice(0,30));const t=message('•••','bot');t.querySelector('.bubble').className='bubble typing';$('#messageInput').value='';setTimeout(()=>{t.querySelector('.bubble').className='bubble';t.querySelector('.bubble').textContent=replies[Math.floor(Math.random()*replies.length)];$('#chatScroll').scrollTop=$('#chatScroll').scrollHeight},700)}
$('#authForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('novaSignedIn','true');$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');newConversation(false)};
if(localStorage.getItem('novaSignedIn')){$('#authScreen').classList.add('hidden');$('#app').classList.remove('hidden');newConversation(false)}
$('#chatForm').onsubmit=e=>{e.preventDefault();send($('#messageInput').value)};$('#messageInput').oninput=e=>{e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,120)+'px'};
document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>send(b.dataset.prompt));$('#newChat').onclick=()=>newConversation();
document.querySelectorAll('.nav-link').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-link,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page+'Page').classList.add('active');closeMenu()});
function closeMenu(){$('#sidebar').classList.remove('open');$('#scrim').classList.remove('show')}$('#menuButton').onclick=()=>{$('#sidebar').classList.add('open');$('#scrim').classList.add('show')};$('#closeSidebar').onclick=closeMenu;$('#scrim').onclick=closeMenu;
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();newConversation()}});
$('#imageForm').onsubmit=e=>{e.preventDefault();const p=$('#imagePrompt').value.trim();if(!p)return $('#imagePrompt').focus();const empty=$('.gallery-empty');if(empty)empty.remove();const card=document.createElement('div');card.className='generated';card.innerHTML=`<strong>${p}</strong><small>Nova Studio · только что</small>`;$('#gallery').prepend(card);$('#imagePrompt').value=''};
